### ISSUE TITLE
0.1.0 TODO

### ISSUE THREAD

**Issue by knuxify** [aspinwall-ui/aspinwall-launcher#3]
This issue outlines the tasks planned for inclusion in the 0.1.0 release. *Previous TODO: #1*

**Do not report issues under this list**; use the "New issue" option instead.

## Launcher

  * [X] Better accessibility (use accessibility labels, etc.) (035cafeb9998700560b13f97aee5863f781a1b97 addresses most of my initial concern by adding tooltips for buttons; this isn't really an actionable task, further improvements will probably be postponed unless someone can suggest any changes)
  * [X] Add "unfocused" mode which hides the side buttons (0af80233a8659a5aa33ab35edc49dc5e1ebf9185)
  * [X] Clock size switch (ec7283d63c366bcf70435f047125dd9ddfb7d7c2)
  * [X] Show widget editing button when hovering a mouse cursor over a widget (96ea477695d62e3a3b1b91bfcb3cb2d92bb98eb5)
  * [X] Decide what to do with GNOME background support; improve it or drop it? (dropped in 78f34e5b81eb7b0874ca3e4f074e57076d6843a9)
  * [X] Consider using a ListBox/ListView for the widget display? (97ad6f5a6edaad7ba5fdad14dcd2d67256b0a89c)
  * [X] Use GridView for app chooser (a85f7f8c40c121b09e8a64dac084cb81fca7fa96)
    * [x] Fix leak when creating long-press gesture (or move the "favorite app" settings somewhere else entirely) (probably out of our control; 0404c8d23407d760757623560aacce7c24fdd581 makes it a bit better)
    * [x] Also make the background look nicer, since it's a little awkward in its current form
  * [x] Add PM/AM indicator
  * [x] Make clicking outside the selected widget undo the selection (b6a042fac56c8d19ca880ecd3e3b16c42e15d9fe)
  * [x] Fix widget drag-and-drop on touchscreens (just got rid of it instead)
  * [X] Redesign widget add dialog (7fed75b30774f57d1d1a016148c64701f942c972)
     * [x] More feedback when adding a widget (scroll to the bottom of the widget list, show a notification)
  * [X] Fix buggy behavior in widget management mode (80396049b5efbae6ee75d75f932ccfbdced5aee7)
  * [X] Add option to quit launcher (6c6c29ea70c9d15079d7bd7e94fe781839974911)
  * [X] Add option to change widget refresh rate in settings (33bb0fe88ebdd2f47c71c85e4604ead9068cb211)
  * [X] Replace most counter threads with a central clock-based system (the "tick" system as seen in c4b45b8244cfc9355f1e1652620afebfe20fa1af) (f0b5fea6b75771b3f9c064a5c15b36ce9782842f)

### Settings
  * [x] Clean up code

## Widgets

  * [X] Weather (0f37a334510f84be55c49c91f722f90aac898965)
  * [X] To-do list (ed8e511836fff6c1d110882f45e2d8eac6d1b482)
  * [X] World clock (d7efdc7869c6cae95a9933347a203c8f45fc27c8)
  * [ ] Calendar
  * [ ] Improve Notepad widget (suggested idea - "daily log" with a daily note rotation and save functionality)
  * [x] Add API for using .ui files 
  * [x] Add refresh button to widget header for widgets that can utilize it
  * [x] Add nicer error messages on widget exceptions (0175e4d)
  * [x] Add guide on packaging widgets

## Low-priority

  * "No distractions" theme - pure black background, white text, only a few select widgets (might be postponed, but it's an idea to consider)
  * Figure out how to split the idle mode/slideshow switch frequency combobox entries; in some languages, these cannot be translated the same, although they are the same in English
  * Feed reader widget
  * Quick shortcuts/app launcher widget
  * Figure out how to deal with translations in widget .ui files?

Tests also need some major improvements.
